http:
  routers:
    adguard:
      entryPoints:
        - https
      rule: "Host(`adguard.corsair.tf`)"
      service: adguard
      priority: 1
      middlewares:
        - private@file
        - security@file
        
  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://192.168.1.8:3000"