http:
  routers:
    truenas:
      entryPoints:
        - https
      rule: "Host(`truenas.corsair.tf`)"
      service: truenas
      priority: 1
      middlewares:
        - private@file
        - security-soft@file
        
  services:
    truenas:
      loadBalancer:
        servers:
          - url: "http://192.168.1.8:8080"