http:
  routers:
    adguard:
      entryPoints:
        - https
      rule: "Host(`dns.corsair.tf`)"
      service: adguard
      priority: 1
      middlewares:
        - security@file
        - private@file
        - auth@docker
        
  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:3000"