http:
  routers:
    homeassistant:
      entryPoints:
        - https
      rule: "Host(`home.corsair.tf`)"
      service: homeassistant
      priority: 1
      middlewares:
        - private@file
        - security-soft@file
        
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.1.8:8123"