services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Must run as root for DHCP raw socket access
    network_mode: host
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=Europe/Paris
      - PUID=3000
      - PGID=3002

  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: iSponsorBlockTV
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./isponsorblocktv:/app/data
    environment:
      - TZ=Europe/Paris
      - PUID=3000
      - PGID=3002