services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    env_file:
      - .env
    volumes:
      - ./traefik:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=(Host(`traefik.corsair.tf`) && !Path(`/metrics`))
      - traefik.http.routers.traefik.tls.domains[0].main=corsair.tf
      - traefik.http.routers.traefik.tls.domains[0].sans=*.corsair.tf
      - traefik.http.routers.traefik.middlewares=private@file,security@file,auth@docker
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=443
      - traefik.http.routers.traefik-metrics.entrypoints=https
      - traefik.http.routers.traefik-metrics.rule=(Host(`traefik.corsair.tf`) && Path(`/metrics`))
      - traefik.http.routers.traefik-metrics.middlewares=private@file,security@file,auth@docker
      - traefik.http.routers.traefik-metrics.service=prometheus@internal

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/linux Dominic-Wagner/vaultwarden
      - GID=3002
      - UID=3000
      - CUSTOM_HOSTNAME=crowdsec
    volumes:
      - ./crowdsec/config:/etc/crowdsec
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./traefik/logs:/var/log/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v4
    container_name: tinyauth
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.entrypoints=https
      - traefik.http.routers.auth.rule=Host(`login.corsair.tf`)
      - traefik.http.routers.auth.service=auth
      - traefik.http.routers.auth.middlewares=security@file
      - traefik.http.services.auth.loadbalancer.server.port=3000
      - traefik.http.middlewares.auth.forwardauth.address=http://tinyauth:3000/api/auth/traefik

networks:
  traefik:
    external: true
